# Generated by Django 3.0.8 on 2020-11-29 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(default='', max_length=255)),
                ('phone_no', models.IntegerField(max_length=10)),
                ('age', models.IntegerField(default=0)),
            ],
        ),
    ]
